# This is a basic workflow to help you get started with Actions

name: Synfig Studio CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15
    #runs-on: macos-11.0
    name: MacOS 10.15 Catalina

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Prepare ccache timestamp
        id: ccache_timestamp
        run: echo "::set-output name=timestamp::`date "+%Y%m%d-%H%M%S"`"
        
      - name: Download ccache archive
        id: ccache-archive
        uses: actions/cache@v2.1.3
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ steps.ccache_timestamp.outputs.timestamp }}
          restore-keys:
            ${{ runner.os }}-ccache-

      - name: Install dependencies (Brew)
        env:
          HOMEBREW_NO_AUTO_UPDATE: 0
          HOMEBREW_NO_ANALYTICS: 1
        #run: ./1-setup-osx-brew.sh
        run: brew install ccache

      - name: Setup ccache parameters and show statistics
        run: |
          ccache --set-config=compression=true
          ccache --directory ${GITHUB_WORKSPACE}/.ccache
          ccache --show-stats
          ccache --show-config

      - name: Build (CMake+Ninja)
        run: |
          brew install ninja
          mkdir build-cmake && cd build-cmake
          cmake -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_BUILD_TYPE=Release ..
          ninja

      - name: ccache statistics
        run: ccache -s
