# This is a basic workflow to help you get started with Actions

name: Synfig Studio CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15
    #runs-on: macos-11.0
    name: MacOS 10.15 Catalina

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Cache brew bottles
        id: cache-bottles
        uses: actions/cache@v2.1.3
        with:
          path: /Users/runner/Library/Caches/Homebrew/
          key: ${{ runner.os }}-brew-bottles-3

      # Runs a single command using the runners shell
      - name: Install Dependencies (Brew)
        env:
          HOMEBREW_NO_AUTO_UPDATE: 0
          HOMEBREW_NO_ANALYTICS: 1
        #if: steps.cache-bottles.outputs.cache-hit != 'true'
        #run: echo "Hello world! (`date`)" >> $HOME/Library/Caches/Homebrew/testfile.txt
        run: ./1-setup-osx-brew.sh

      # Runs a set of commands using the runners shell
      - name: Build (CMake)
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          cat $HOME/Library/Caches/Homebrew/testfile.txt
